spring:
  data:
    mongodb:
      uri: ${MONGO_URL}
      auto-index-creation: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html

application-description: teste
application-version: 0.0.1

logging:
  level:
    root: INFO